parameters:
#    cluddy_welcome.example.class: Cluddy\WelcomeBundle\Example

services:
#    cluddy_welcome.example:
#        class: %cluddy_welcome.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
